"""empty message

Revision ID: 4964024f9ebd
Revises: 
Create Date: 2020-05-15 22:06:12.510681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4964024f9ebd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthdays')
    # ### end Alembic commands ###
